/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion.empleados.opciones.registros.obtenidos;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import validaciones.*;
import entidades.*;
import seguridad.Autenticacion;

/**
 *
 * @author Roberto
 */
public class IFrmDatosClienteObtenidos extends javax.swing.JInternalFrame {
    public static IFrmDatosClienteObtenidos form = null;
    /**
     * Creates new form FrmDatosCuentaObtenidos
     */
    private IFrmDatosClienteObtenidos() {
        initComponents();
        try {
            tipEmpleado.setText(Autenticacion.obtenerUsuario().getCodigo());
        } catch (IllegalStateException e){
            JOptionPane.showMessageDialog(this, "Autenticación | No se puede continuar: No existe una sesión iniciada.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Datos de una Cuenta | Ha ocurrido un problema mientras nos conectabamos a la BD. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tipAccion = new javax.swing.JLabel();
        tipEmpleado = new javax.swing.JLabel();
        labelDNI = new javax.swing.JLabel();
        labelCodigoCliente = new javax.swing.JLabel();
        labelNombres = new javax.swing.JLabel();
        labelApellidoPaterno = new javax.swing.JLabel();
        labelApellidoMaterno = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelNombreUsuario = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(914, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 45, 68));

        tituloPanel.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(229, 229, 229));
        tituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanel.setText("Estás observando los datos de un cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipAccion.setForeground(new java.awt.Color(0, 0, 0));
        tipAccion.setText("Esta es una acción de empleado autorizada para:");
        jPanel2.add(tipAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tipEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        tipEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipEmpleado.setText("usuarioPlaceholder");
        jPanel2.add(tipEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 164, -1));

        labelDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDNI.setForeground(new java.awt.Color(0, 0, 0));
        labelDNI.setText("DNI:");
        jPanel2.add(labelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        labelCodigoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigoCliente.setForeground(new java.awt.Color(0, 0, 0));
        labelCodigoCliente.setText("Código de Cliente:");
        jPanel2.add(labelCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        labelNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombres.setForeground(new java.awt.Color(0, 0, 0));
        labelNombres.setText("Nombres:");
        jPanel2.add(labelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        labelApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelApellidoPaterno.setForeground(new java.awt.Color(0, 0, 0));
        labelApellidoPaterno.setText("Apellido paterno:");
        jPanel2.add(labelApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        labelApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelApellidoMaterno.setForeground(new java.awt.Color(0, 0, 0));
        labelApellidoMaterno.setText("Apellido materno:");
        jPanel2.add(labelApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        labelCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCiudad.setForeground(new java.awt.Color(0, 0, 0));
        labelCiudad.setText("Ciudad:");
        jPanel2.add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        labelDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDireccion.setForeground(new java.awt.Color(0, 0, 0));
        labelDireccion.setText("Dirección:");
        jPanel2.add(labelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(0, 0, 0));
        labelTelefono.setText("Teléfono:");
        jPanel2.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 0, 0));
        labelEmail.setText("Email:");
        jPanel2.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        labelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        labelNombreUsuario.setText("Nombre de Usuario:");
        jPanel2.add(labelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        txtApellidoMaterno.setEnabled(false);
        jPanel2.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 210, -1));

        txtCodigoCliente.setEnabled(false);
        jPanel2.add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 210, -1));

        txtDNI.setEnabled(false);
        jPanel2.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 210, -1));

        txtNombres.setEnabled(false);
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 210, -1));

        txtApellidoPaterno.setEnabled(false);
        jPanel2.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 210, -1));

        txtCiudad.setEnabled(false);
        jPanel2.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 210, -1));

        txtDireccion.setEnabled(false);
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 210, -1));

        txtTelefono.setEnabled(false);
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 210, -1));

        txtEmail.setEnabled(false);
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 210, -1));

        txtNombreUsuario.setEnabled(false);
        jPanel2.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static IFrmDatosClienteObtenidos getInstance(Cliente cliente){
        form = new IFrmDatosClienteObtenidos();
        form.rellenarInformacion(cliente);
        return form;
    }
    
    private void rellenarInformacion(Cliente cliente){
        try {  
            /* Empiezan los datos del Cliente */
            txtCodigoCliente.setText(cliente.getCodigo());
            txtDNI.setText(cliente.getDni());
            txtNombres.setText(cliente.getNombre());
            txtApellidoPaterno.setText(cliente.getApellidoPaterno());
            txtApellidoMaterno.setText(cliente.getApellidoMaterno());
            txtCiudad.setText(cliente.getCiudad());
            txtDireccion.setText(cliente.getDireccion());
            txtTelefono.setText(cliente.getTelefono());
            txtEmail.setText(cliente.getEmail());
            txtNombreUsuario.setText(Usuarios.obtenerUsuario(cliente.getIdUsuario()).getCodigo());
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Datos de un Cliente | Tuvimos un problema conectándonos a la base de datos. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelApellidoMaterno;
    private javax.swing.JLabel labelApellidoPaterno;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelCodigoCliente;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel tipAccion;
    private javax.swing.JLabel tipEmpleado;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
