/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion.administrador.opciones.empleados;

import entidades.Empleado;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import validaciones.Empleados;

/**
 *
 * @author Jorge
 */
public class IFrmModificarEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmModificarEmpleados
     */
    public IFrmModificarEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblPaterno = new javax.swing.JLabel();
        lblMaterno = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(229, 229, 229));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(588, 541));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 45, 68));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 229, 229));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estás modificando a un Empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 576, -1));

        jPanel2.setBackground(new java.awt.Color(227, 227, 227));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("Codigo:");
        jPanel2.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 82, 27));

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 250, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.gif"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 130, -1));

        lblNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 82, 27));

        lblPaterno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPaterno.setForeground(new java.awt.Color(0, 0, 0));
        lblPaterno.setText("Apellido Paterno:");
        jPanel2.add(lblPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 27));

        lblMaterno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMaterno.setForeground(new java.awt.Color(0, 0, 0));
        lblMaterno.setText("Apellido Materno:");
        jPanel2.add(lblMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 27));

        lblCiudad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCiudad.setForeground(new java.awt.Color(0, 0, 0));
        lblCiudad.setText("Ciudad:");
        jPanel2.add(lblCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 82, 27));

        lblDireccion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccion.setText("Direccion:");
        jPanel2.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 82, 27));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setEnabled(false);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 170, -1));

        txtPaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtPaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPaterno.setForeground(new java.awt.Color(0, 0, 0));
        txtPaterno.setEnabled(false);
        jPanel2.add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 170, -1));

        txtMaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtMaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtMaterno.setForeground(new java.awt.Color(0, 0, 0));
        txtMaterno.setEnabled(false);
        jPanel2.add(txtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 170, -1));

        txtCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtCiudad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad.setEnabled(false);
        jPanel2.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 170, -1));

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setEnabled(false);
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 170, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/style_file.gif"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 134, 42));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 580, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void activar(boolean estado) {
        txtCodigo.setEnabled(!estado);
        txtNombre.setEnabled(estado);
        txtPaterno.setEnabled(estado);
        txtMaterno.setEnabled(estado);
        txtCiudad.setEnabled(estado);
        txtDireccion.setEnabled(estado);
        btnBuscar.setEnabled(!estado);
        btnActualizar.setEnabled(estado);
    }
    
    private void limpiar() {
        txtCodigo.setText(null);
        txtNombre.setText(null);
        txtPaterno.setText(null);
        txtMaterno.setText(null);
        txtCiudad.setText(null);
        txtDireccion.setText(null);
    }
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        final String ERROR_TITULO = "Un problema ha ocurrido...";

        String codigo = txtCodigo.getText();
        Empleado empleado = null;
        try {
            empleado = Empleados.obtener(codigo);
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        } catch (IllegalStateException e){
            JOptionPane.showMessageDialog(this, "Autenticación | No se puede continuar: No existe una sesión iniciada.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Datos de una Cuenta | Ha ocurrido un problema mientras nos conectabamos a la BD. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
        
        if (empleado == null){
            JOptionPane.showMessageDialog(this, "El código no es valido.", ERROR_TITULO, 0);
            limpiar();
            activar(false);
        }
        
        txtNombre.setText(String.valueOf(empleado.getNombre()));
        txtPaterno.setText(String.valueOf(empleado.getApellidoPaterno()));
        txtMaterno.setText(String.valueOf(empleado.getApellidoMaterno()));
        txtCiudad.setText(String.valueOf(empleado.getCiudad()));
        txtDireccion.setText(String.valueOf(empleado.getDireccion()));
        activar(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        final String CORRECTO_TITULO = "Operación realizada";
        try {
            Empleados.modificarNombre(txtCodigo.getText(),txtNombre.getText());
            Empleados.modificarApellidoPaterno(txtCodigo.getText(),txtPaterno.getText());
            Empleados.modificarApellidoMaterno(txtCodigo.getText(),txtMaterno.getText());
            Empleados.modificarCiudad(txtCodigo.getText(),txtCiudad.getText());
            Empleados.modificarDireccion(txtCodigo.getText(),txtDireccion.getText());
            Empleados.modificarNombre(txtCodigo.getText(),txtNombre.getText());

            JOptionPane.showMessageDialog(this, "Se actualizo correctamente.", CORRECTO_TITULO, JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(IFrmModificarEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblMaterno;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPaterno;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    // End of variables declaration//GEN-END:variables
}
