/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion.empleados.opciones.registros;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import validaciones.*;
import entidades.*;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.ArrayList;
import java.util.Iterator;
import seguridad.Autenticacion;
import seguridad.Contrasenas;

/**
 *
 * @author Roberto
 */
public class IFrmRegistrarCuenta extends javax.swing.JInternalFrame {
    public static IFrmRegistrarCuenta form = null;
    private static ArrayList<Moneda> monedasDisponibles = null;
    private static ArrayList<Sucursal> sucursalesDisponibles = null;
    /**
     * Creates new form FrmDatosCuentaObtenidos
     */
    private IFrmRegistrarCuenta() {
        initComponents();
        try {
            tipEmpleado.setText(Autenticacion.obtenerUsuario().getCodigo());
            
            /* Agregar monedas disponibles a su combobox respectivo */
            monedasDisponibles = Monedas.listarMonedas();
            Iterator<Moneda> iteradorM = monedasDisponibles.iterator();
            
            while (iteradorM.hasNext()){
                Moneda m = iteradorM.next();
                cbxMoneda.addItem(m.getDescripcion());
            }
            
            /* Agregar Sucursales disponibles a su combobox respectivo */
            sucursalesDisponibles = Sucursales.listarSucursales();
            Iterator<Sucursal> iteradorS = sucursalesDisponibles.iterator();
            
            while (iteradorS.hasNext()){
                Sucursal s = iteradorS.next();
                cbxSucursal.addItem(s.getNombre());
            }
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        } catch (IllegalStateException e){
            JOptionPane.showMessageDialog(this, "Autenticación | No se puede continuar: No existe una sesión iniciada.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Datos de una Cuenta | Ha ocurrido un problema mientras nos conectabamos a la BD. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tipAccion = new javax.swing.JLabel();
        tipEmpleado = new javax.swing.JLabel();
        labelMoneda = new javax.swing.JLabel();
        cbxMoneda = new javax.swing.JComboBox<>();
        cbxSucursal = new javax.swing.JComboBox<>();
        labelSucursal = new javax.swing.JLabel();
        labelClaveCajero = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        labelCodigoCliente = new javax.swing.JLabel();
        pwdClaveCajero = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(630, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 45, 68));

        tituloPanel.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(229, 229, 229));
        tituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanel.setText("Estás registrando una nueva cuenta para un cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 70));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipAccion.setForeground(new java.awt.Color(0, 0, 0));
        tipAccion.setText("Esta es una acción de empleado autorizada para:");
        jPanel2.add(tipAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tipEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        tipEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipEmpleado.setText("usuarioPlaceholder");
        jPanel2.add(tipEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 164, -1));

        labelMoneda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMoneda.setForeground(new java.awt.Color(0, 0, 0));
        labelMoneda.setText("Moneda de la cuenta:");
        jPanel2.add(labelMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 160, -1));

        jPanel2.add(cbxMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 150, -1));

        jPanel2.add(cbxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 150, -1));

        labelSucursal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSucursal.setForeground(new java.awt.Color(0, 0, 0));
        labelSucursal.setText("Sucursal:");
        jPanel2.add(labelSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        labelClaveCajero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelClaveCajero.setForeground(new java.awt.Color(0, 0, 0));
        labelClaveCajero.setText("Clave de cajero:");
        jPanel2.add(labelClaveCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 130, -1));
        jPanel2.add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 150, -1));

        labelCodigoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigoCliente.setForeground(new java.awt.Color(0, 0, 0));
        labelCodigoCliente.setText("Codigo de Cliente:");
        jPanel2.add(labelCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));
        jPanel2.add(pwdClaveCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 150, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 620, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            String codigoCliente = txtCodigoCliente.getText();
            if (cbxMoneda.getSelectedIndex() == -1) throw new IllegalArgumentException("Se tiene que seleccionar una sucursal válida.");
            if (cbxSucursal.getSelectedIndex() == -1) throw new IllegalArgumentException("Se tiene que seleccionar una sucursal válida.");
            String codigoMoneda = monedasDisponibles.get(cbxMoneda.getSelectedIndex()).getCodigo();
            String codigoSucursal = sucursalesDisponibles.get(cbxSucursal.getSelectedIndex()).getCodigo();
            String codigoCajero = String.valueOf(pwdClaveCajero.getPassword());
            String codigoCuenta = Cuentas.generarCodigo();
            String codigoUsuario = Clientes.obtener(codigoCliente).getIdUsuario();
            
            Cuentas.agregar(codigoCuenta, codigoMoneda, codigoSucursal, codigoCliente, codigoUsuario, 0, codigoCajero);
            JOptionPane.showMessageDialog(this, "Cuenta creada correctamente. Código de cuenta: " + codigoCuenta, "La operación se ha realizado con éxito.", JOptionPane.INFORMATION_MESSAGE);
        } catch (InvalidKeySpecException | NoSuchAlgorithmException | NullPointerException e){
            JOptionPane.showMessageDialog(null, "Autenticación: Ha ocurrido un problema grave. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
            System.out.println(e.getLocalizedMessage());
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Registrar una nueva cuenta | Ha ocurrido un problema mientras nos conectabamos a la BD. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    public static IFrmRegistrarCuenta getInstance(){
        form = new IFrmRegistrarCuenta();
        return form;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxMoneda;
    private javax.swing.JComboBox<String> cbxSucursal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelClaveCajero;
    private javax.swing.JLabel labelCodigoCliente;
    private javax.swing.JLabel labelMoneda;
    private javax.swing.JLabel labelSucursal;
    private javax.swing.JPasswordField pwdClaveCajero;
    private javax.swing.JLabel tipAccion;
    private javax.swing.JLabel tipEmpleado;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JTextField txtCodigoCliente;
    // End of variables declaration//GEN-END:variables
}
