/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.clientes.registro;

import entidades.Cliente;
import javax.swing.JOptionPane;
import presentacion.login.Login;

/**
 *
 * @author Roberto
 */
public class Registro extends javax.swing.JFrame {
    private static Registro form = null;
    private String fuente = "login";
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tipCompletaForm = new javax.swing.JLabel();
        labelNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        labelApellidoPaterno = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        labelApellidoMaterno = new javax.swing.JLabel();
        labelDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        tituloEmpecemos = new javax.swing.JLabel();
        tipEmpecemos = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnPaso2 = new javax.swing.JButton();
        labelCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        btnRegresarLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 45, 68));

        tituloPanel.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(229, 229, 229));
        tituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanel.setText("¡Te damos la bienvenida a la familia EurekaBank!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipCompletaForm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tipCompletaForm.setForeground(new java.awt.Color(0, 0, 0));
        tipCompletaForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipCompletaForm.setText("Por favor, completa el siguiente formulario:");
        jPanel2.add(tipCompletaForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 900, -1));

        labelNombres.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNombres.setForeground(new java.awt.Color(0, 0, 0));
        labelNombres.setText("Nombres");
        jPanel2.add(labelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 219, -1, -1));
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 242, 315, -1));

        labelApellidoPaterno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelApellidoPaterno.setForeground(new java.awt.Color(0, 0, 0));
        labelApellidoPaterno.setText("Apellido paterno");
        jPanel2.add(labelApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 286, -1, -1));
        jPanel2.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 309, 315, -1));
        jPanel2.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 376, 315, -1));

        labelApellidoMaterno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelApellidoMaterno.setForeground(new java.awt.Color(0, 0, 0));
        labelApellidoMaterno.setText("Apellido materno");
        jPanel2.add(labelApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 353, -1, -1));

        labelDNI.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelDNI.setForeground(new java.awt.Color(0, 0, 0));
        labelDNI.setText("DNI");
        jPanel2.add(labelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 164, -1, -1));
        jPanel2.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 187, 178, -1));

        tituloEmpecemos.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tituloEmpecemos.setForeground(new java.awt.Color(0, 0, 0));
        tituloEmpecemos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloEmpecemos.setText("Empecemos la creación de tu nueva cuenta");
        jPanel2.add(tituloEmpecemos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, 900, -1));

        tipEmpecemos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tipEmpecemos.setForeground(new java.awt.Color(0, 0, 0));
        tipEmpecemos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipEmpecemos.setText("Por tu seguridad, debemos validar tus datos");
        jPanel2.add(tipEmpecemos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, 900, -1));

        labelDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDireccion.setForeground(new java.awt.Color(0, 0, 0));
        labelDireccion.setText("Dirección");
        jPanel2.add(labelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 219, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(0, 0, 0));
        labelTelefono.setText("Teléfono");
        jPanel2.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 286, -1, -1));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 309, 171, -1));

        labelEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 0, 0));
        labelEmail.setText("Email");
        jPanel2.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 353, -1, -1));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 376, 315, -1));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 242, 315, -1));

        btnPaso2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPaso2.setText("¡Quiero mi nueva cuenta!");
        btnPaso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaso2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPaso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 198, 47));

        labelCiudad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCiudad.setForeground(new java.awt.Color(0, 0, 0));
        labelCiudad.setText("Ciudad");
        jPanel2.add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 164, -1, -1));
        jPanel2.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 187, 315, -1));

        btnRegresarLogin.setText("No, ya tengo cuenta");
        btnRegresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 481, 155, 38));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarLoginActionPerformed
        this.setVisible(false);
        Login login = Login.getInstance();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarLoginActionPerformed

    private void btnPaso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaso2ActionPerformed
        String dni = txtDNI.getText();
        String nombres = txtNombres.getText();
        String apellidoPaterno = txtApellidoPaterno.getText();
        String apellidoMaterno = txtApellidoMaterno.getText();
        String ciudad = txtCiudad.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        String email = txtEmail.getText();

        if (!verificarRestricciones()) return;

        Cliente c = new Cliente();
        c.setDni(dni);
        c.setNombre(nombres);
        c.setApellidoPaterno(apellidoPaterno);
        c.setApellidoMaterno(apellidoMaterno);
        c.setCiudad(ciudad);
        c.setDireccion(direccion);
        c.setTelefono(telefono);
        c.setEmail(email);

        RegistroPaso2 reg2 = RegistroPaso2.getInstance(c, fuente);
        this.setVisible(false);
        reg2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPaso2ActionPerformed
    
    private boolean verificarRestricciones(){
        String dni = txtDNI.getText();
        String nombres = txtNombres.getText();
        String apellidoPaterno = txtApellidoPaterno.getText();
        String apellidoMaterno = txtApellidoMaterno.getText();
        String ciudad = txtCiudad.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        String email = txtEmail.getText();
        
        if (dni.isBlank()){
            JOPFallo("DNI");
            return false;
        }
        
        if (dni.length() != 8){
            JOptionPane.showMessageDialog(this, "Paso 1 del Registro | El DNI tiene que tener 8 caracteres.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            return false;
        }
            
        if (nombres.isBlank()){
            JOPFallo("nombres");
            return false;
        }
        if (apellidoPaterno.isBlank()){
            JOPFallo("apellido paterno");
            return false;
        }
        if (apellidoMaterno.isBlank()){
            JOPFallo("apellido materno");
            return false;
        }
        if (ciudad.isBlank()){
            JOPFallo("ciudad");
            return false;
        }
        if (direccion.isBlank()){
            JOPFallo("dirección");
            return false;
        }
        if (telefono.isBlank()){
            JOPFallo("teléfono");
            return false;
        }
        if (email.isBlank()){
            JOPFallo("email");
            return false;
        }
        
        return true;
    }
    
    private void JOPFallo(String campo){
        JOptionPane.showMessageDialog(this, "Paso 1 del Registro | El campo de " + campo + " no puede estar vacío.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    private static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    
    private void setFuente(String fuente){
        this.fuente = fuente;
    }
    
    public static Registro getInstance(String fuente){
        if (form == null) form = new Registro();
        if (fuente.equalsIgnoreCase("login")) form.setFuente("login");
        if (fuente.equalsIgnoreCase("empleados")) {
            form.setFuente("empleados");
            form.btnRegresarLogin.setVisible(false);
        }
        return form;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaso2;
    private javax.swing.JButton btnRegresarLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelApellidoMaterno;
    private javax.swing.JLabel labelApellidoPaterno;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel tipCompletaForm;
    private javax.swing.JLabel tipEmpecemos;
    private javax.swing.JLabel tituloEmpecemos;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
