/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion.empleados.opciones.operaciones;

import presentacion.clientes.opciones.transacciones.*;
import presentacion.clientes.opciones.cuentas.*;
import presentacion.empleados.opciones.registros.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import validaciones.*;
import entidades.*;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import operaciones.GestorTransacciones;
import presentacion.FrmClientes;
import presentacion.empleados.FrmEmpleado;
import seguridad.Autenticacion;
import seguridad.Contrasenas;

/**
 *
 * @author Roberto
 */
public class IFrmRealizarDeposito extends javax.swing.JInternalFrame {
    public static IFrmRealizarDeposito form = null;
    /**
     * Creates new form FrmDatosCuentaObtenidos
     */
    private IFrmRealizarDeposito() {
        initComponents();
        try {
            tipEmpleado.setText(Autenticacion.obtenerUsuario().getCodigo());
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        } catch (IllegalStateException e){
            JOptionPane.showMessageDialog(this, "Autenticación | No se puede continuar: No existe una sesión iniciada.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Depósitos | Ha ocurrido un problema mientras nos conectabamos a la BD. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelMonto = new javax.swing.JLabel();
        btnRealizarDeposito = new javax.swing.JButton();
        tipRealizandoTransf = new javax.swing.JLabel();
        tipNumeroCuenta = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        tipAccionEmpleado = new javax.swing.JLabel();
        tipEmpleado = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(630, 383));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 45, 68));

        tituloPanel.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(229, 229, 229));
        tituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanel.setText("Realizar un depósito a una cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 70));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMonto.setForeground(new java.awt.Color(0, 0, 0));
        labelMonto.setText("Monto:");
        jPanel2.add(labelMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        btnRealizarDeposito.setText("Realizar depósito");
        btnRealizarDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarDepositoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRealizarDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 190, 50));

        tipRealizandoTransf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tipRealizandoTransf.setForeground(new java.awt.Color(0, 0, 0));
        tipRealizandoTransf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipRealizandoTransf.setText("Estás realizando un depósito");
        jPanel2.add(tipRealizandoTransf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 620, -1));

        tipNumeroCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipNumeroCuenta.setForeground(new java.awt.Color(0, 0, 0));
        tipNumeroCuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tipNumeroCuenta.setText("Introduce el número de cuenta:");
        jPanel2.add(tipNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 200, -1));

        txtNumeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCuentaActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 320, -1));
        jPanel2.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 130, -1));

        tipAccionEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        tipAccionEmpleado.setText("Esta es una acción de empleado autorizada para:");
        jPanel2.add(tipAccionEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        tipEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        tipEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipEmpleado.setText("usuarioPlaceholder");
        jPanel2.add(tipEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 164, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 620, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnRealizarDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarDepositoActionPerformed
        try {
            Empleado empleado = Empleados.obtenerPorIdUsuario(Autenticacion.obtenerUsuario().getCodigo());
            Cuenta cuenta = Cuentas.obtener(txtNumeroCuenta.getText());
            float monto = Float.parseFloat(txtMonto.getText());
            
            GestorTransacciones.depositar(cuenta.getCodigo(), monto, empleado.getCodigo());
            JOptionPane.showMessageDialog(this, "El depósito se realizó correctamente.", "Depósito realizado", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        } catch (IllegalStateException e){
            JOptionPane.showMessageDialog(this, "Autenticación | No se puede continuar: No existe una sesión iniciada.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Depósitos | Ha ocurrido un problema mientras nos conectabamos a la BD. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnRealizarDepositoActionPerformed

    private void txtNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuentaActionPerformed
    
    public static IFrmRealizarDeposito getInstance(){
        form = new IFrmRealizarDeposito();
        return form;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarDeposito;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelMonto;
    private javax.swing.JLabel tipAccionEmpleado;
    private javax.swing.JLabel tipEmpleado;
    private javax.swing.JLabel tipNumeroCuenta;
    private javax.swing.JLabel tipRealizandoTransf;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
