/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion.empleados.opciones;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import validaciones.*;
import entidades.*;
import seguridad.Autenticacion;

/**
 *
 * @author Roberto
 */
public class IFrmDatosCuentaObtenidos extends javax.swing.JInternalFrame {
    public static IFrmDatosCuentaObtenidos form = null;
    /**
     * Creates new form FrmDatosCuentaObtenidos
     */
    private IFrmDatosCuentaObtenidos() {
        initComponents();
        try {
            tipEmpleado.setText(Autenticacion.obtenerUsuario().getCodigo());
        } catch (IllegalStateException e){
            JOptionPane.showMessageDialog(this, "Autenticación | No se puede continuar: No existe una sesión iniciada.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Datos de una Cuenta | Ha ocurrido un problema mientras nos conectabamos a la BD. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tipAccion = new javax.swing.JLabel();
        tipEmpleado = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        labelMoneda = new javax.swing.JLabel();
        txtMoneda = new javax.swing.JTextField();
        labelSucursal = new javax.swing.JLabel();
        txtSucursal = new javax.swing.JTextField();
        labelDNI = new javax.swing.JLabel();
        labelTituloCliente = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        labelFechaCreacion = new javax.swing.JLabel();
        txtFechaCreacion = new javax.swing.JTextField();
        labelCantidadMovimientos = new javax.swing.JLabel();
        txtCantidadMovimientos = new javax.swing.JTextField();
        labelCodigoCliente = new javax.swing.JLabel();
        labelNombres = new javax.swing.JLabel();
        labelApellidoPaterno = new javax.swing.JLabel();
        labelApellidoMaterno = new javax.swing.JLabel();
        labelCiudad = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelNombreUsuario = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 45, 68));

        tituloPanel.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(229, 229, 229));
        tituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanel.setText("Estás observando los datos de una cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipAccion.setForeground(new java.awt.Color(0, 0, 0));
        tipAccion.setText("Esta es una acción de empleado autorizada para:");
        jPanel2.add(tipAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tipEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        tipEmpleado.setText("usuarioPlaceholder");
        jPanel2.add(tipEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 164, -1));

        labelCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigo.setForeground(new java.awt.Color(0, 0, 0));
        labelCodigo.setText("Código:");
        jPanel2.add(labelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        txtCodigo.setEnabled(false);
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 172, -1));

        labelMoneda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMoneda.setForeground(new java.awt.Color(0, 0, 0));
        labelMoneda.setText("Moneda:");
        jPanel2.add(labelMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        txtMoneda.setEnabled(false);
        jPanel2.add(txtMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 172, -1));

        labelSucursal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSucursal.setForeground(new java.awt.Color(0, 0, 0));
        labelSucursal.setText("Sucursal:");
        jPanel2.add(labelSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        txtSucursal.setEnabled(false);
        jPanel2.add(txtSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 172, -1));

        labelDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDNI.setForeground(new java.awt.Color(0, 0, 0));
        labelDNI.setText("DNI:");
        jPanel2.add(labelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        labelTituloCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTituloCliente.setForeground(new java.awt.Color(0, 0, 0));
        labelTituloCliente.setText("Datos del Cliente");
        jPanel2.add(labelTituloCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        labelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSaldo.setForeground(new java.awt.Color(0, 0, 0));
        labelSaldo.setText("Saldo:");
        jPanel2.add(labelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        txtSaldo.setEnabled(false);
        jPanel2.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 172, -1));

        labelFechaCreacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelFechaCreacion.setForeground(new java.awt.Color(0, 0, 0));
        labelFechaCreacion.setText("Fecha de Creación:");
        jPanel2.add(labelFechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        txtFechaCreacion.setEnabled(false);
        jPanel2.add(txtFechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 172, -1));

        labelCantidadMovimientos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCantidadMovimientos.setForeground(new java.awt.Color(0, 0, 0));
        labelCantidadMovimientos.setText("Cantidad de Movimientos:");
        jPanel2.add(labelCantidadMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        txtCantidadMovimientos.setEnabled(false);
        jPanel2.add(txtCantidadMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 172, -1));

        labelCodigoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigoCliente.setForeground(new java.awt.Color(0, 0, 0));
        labelCodigoCliente.setText("Código de Cliente:");
        jPanel2.add(labelCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        labelNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombres.setForeground(new java.awt.Color(0, 0, 0));
        labelNombres.setText("Nombres:");
        jPanel2.add(labelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        labelApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelApellidoPaterno.setForeground(new java.awt.Color(0, 0, 0));
        labelApellidoPaterno.setText("Apellido paterno:");
        jPanel2.add(labelApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        labelApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelApellidoMaterno.setForeground(new java.awt.Color(0, 0, 0));
        labelApellidoMaterno.setText("Apellido materno:");
        jPanel2.add(labelApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        labelCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCiudad.setForeground(new java.awt.Color(0, 0, 0));
        labelCiudad.setText("Ciudad:");
        jPanel2.add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        labelDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDireccion.setForeground(new java.awt.Color(0, 0, 0));
        labelDireccion.setText("Dirección:");
        jPanel2.add(labelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(0, 0, 0));
        labelTelefono.setText("Teléfono:");
        jPanel2.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 0, 0));
        labelEmail.setText("Email:");
        jPanel2.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        labelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        labelNombreUsuario.setText("Nombre de Usuario:");
        jPanel2.add(labelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        txtApellidoMaterno.setEnabled(false);
        jPanel2.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 210, -1));

        txtCodigoCliente.setEnabled(false);
        jPanel2.add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 210, -1));

        txtDNI.setEnabled(false);
        jPanel2.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 210, -1));

        txtNombres.setEnabled(false);
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, -1));

        txtApellidoPaterno.setEnabled(false);
        jPanel2.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 210, -1));

        txtCiudad.setEnabled(false);
        jPanel2.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 210, -1));

        txtDireccion.setEnabled(false);
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 210, -1));

        txtTelefono.setEnabled(false);
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 210, -1));

        txtEmail.setEnabled(false);
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 210, -1));

        txtNombreUsuario.setEnabled(false);
        jPanel2.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static IFrmDatosCuentaObtenidos getInstance(Cuenta cuenta){
        form = new IFrmDatosCuentaObtenidos();
        form.rellenarInformacion(cuenta);
        return form;
    }
    
    private void rellenarInformacion(Cuenta cuenta){
        try {
            txtCodigo.setText(cuenta.getCodigo());
            Sucursal sucursal = Sucursales.obtener(cuenta.getCodigoSucursal());
            System.out.println("sucursal: " + sucursal.getNombre());
            txtSucursal.setText(sucursal.getNombre());
            
            Moneda moneda = Monedas.obtener(cuenta.getCodigoMoneda());
            txtMoneda.setText(moneda.getDescripcion());
            
            txtSaldo.setText(String.valueOf(cuenta.getSaldo()));
            txtCantidadMovimientos.setText(String.valueOf(cuenta.getCantidadMovimientos()));
            
            /* Empiezan los datos del Cliente */
            Cliente cliente = Clientes.obtener(cuenta.getCodigoCliente());
            txtCodigoCliente.setText(cliente.getCodigo());
            txtDNI.setText(cliente.getDni());
            txtNombres.setText(cliente.getNombre());
            txtApellidoPaterno.setText(cliente.getApellidoPaterno());
            txtApellidoMaterno.setText(cliente.getApellidoMaterno());
            txtCiudad.setText(cliente.getCiudad());
            txtDireccion.setText(cliente.getDireccion());
            txtTelefono.setText(cliente.getTelefono());
            txtEmail.setText(cliente.getEmail());
            txtNombreUsuario.setText(cliente.getNombre());
            
            /* Convierte la fecha java.sql.Date a String */
            java.util.Date fecha = new java.util.Date(cuenta.getFechaCreacion().getTime());
            SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date fechaFormateada = formateador.parse(fecha.toString());
            txtFechaCreacion.setText(DateFormat.getDateInstance().format(fechaFormateada));
        } catch (NullPointerException | ParseException e){
            // Detecta si el parser falló para la fecha
            JOptionPane.showMessageDialog(this, "Datos de una Cuenta | No se pudo obtener la fecha correctamente.", "Ocurrió un problema...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        } catch (IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Datos de una Cuenta | Ha ocurrido un problema mientras nos conectabamos a la BD. Por favor, cierra el programa y vuelve a intentarlo.", "Un problema ha ocurrido...", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelApellidoMaterno;
    private javax.swing.JLabel labelApellidoPaterno;
    private javax.swing.JLabel labelCantidadMovimientos;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelCodigoCliente;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFechaCreacion;
    private javax.swing.JLabel labelMoneda;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelSucursal;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTituloCliente;
    private javax.swing.JLabel tipAccion;
    private javax.swing.JLabel tipEmpleado;
    private javax.swing.JLabel tituloPanel;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCantidadMovimientos;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtMoneda;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSucursal;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
